# Configuration for LLama Chatbot
llm:
  # Chat model configuration
  model_name: chatglm-6b
  history_len: 3
# Configuration for word embedding model
embedding:
  model_name: text2vec
  # # Device configuration (options: cuda mps cpu)
  device:
# Configuration for vector searching
vector:
  # Top K search results to retrieve
  search_top_k: 5
# Configuration for API server
api_server:
  # Host IP address to bind
  host: 0.0.0.0
  # Port number to listen on
  port: 7862