FROM  nvidia/cuda:12.1.0-runtime-ubuntu20.04
LABEL MAINTAINER="chatGLM"

COPY . /chatGLM/

WORKDIR /chatGLM

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone
RUN apt-get update -y && apt-get install python3 python3-pip curl libgl1 libglib2.0-0 -y  && apt-get clean
RUN /bin/chmod +x /chatGLM/entrypoint.sh
RUN python3 /chatGLM/get-pip.py 

RUN pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple && rm -rf `pip3 cache dir`

ENTRYPOINT ["su","-","root", "-c","/chatGLM/entrypoint.sh"]
#CMD ["python3","-u", "webui.py"]
