credentials:
  usernames:
    john:
      email: jsmith@gmail.com
      name: John Smith
      password: '$2b$12$sH/PcKB5IcU6RxZoLdP4a.KlzhGPGxufD/3on8ZFyNtXPBEFrURTu'
    peter:
      email: petebrriggs@gmail.com
      name: Peter Briggs
      password: '$2b$12$sH/PcKB5IcU6RxZoLdP4a.KlzhGPGxufD/3on8ZFyNtXPBEFrURTu'
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
