name: build

on:
  push:
    branches:
      - "feat/gitAction"

env:
  DOCKERHUB_USERNAME: 100018410921

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/apache/flink/blob/02d30ace69dc18555a5085eccf70ee884e73a16e/tools/azure-pipelines/free_disk_space.sh
      - name: Delete huge unnecessary tools folder
        run: |
          df -h
          echo "Removing large packages"
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
          echo "Removing large directories"
          # deleting 15GB
          rm -rf /opt/hostedtoolcache
          df -h

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Clone model
        run: |
          df -h
          sudo mkdir -p /mnt/chatglm3-6b /mnt/bge-large-zh-v1.5
          
          cd /mnt/chatglm3-6b
          sudo wget https://huggingface.co/THUDM/chatglm3-6b/resolve/main/model-00001-of-00007.safetensors &> /dev/null
          sudo wget https://huggingface.co/THUDM/chatglm3-6b/resolve/main/model-00002-of-00007.safetensors &> /dev/null
          sudo wget https://huggingface.co/THUDM/chatglm3-6b/resolve/main/model-00003-of-00007.safetensors &> /dev/null
          sudo wget https://huggingface.co/THUDM/chatglm3-6b/resolve/main/model-00004-of-00007.safetensors &> /dev/null
          sudo wget https://huggingface.co/THUDM/chatglm3-6b/resolve/main/model-00005-of-00007.safetensors &> /dev/null
          sudo wget https://huggingface.co/THUDM/chatglm3-6b/resolve/main/model-00006-of-00007.safetensors &> /dev/null
          sudo wget https://huggingface.co/THUDM/chatglm3-6b/resolve/main/model-00007-of-00007.safetensors &> /dev/null
          
          cd /mnt/bge-large-zh-v1.5
          sudo wget https://huggingface.co/BAAI/bge-large-zh-v1.5/resolve/main/pytorch_model.bin &> /dev/null
          
          df -h

#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ env.DOCKERHUB_USERNAME }}
##          password: ${{ secrets.DOCKERHUB_TOKEN }}
#          password: junxiezy@930117
      - name: Login to Tencent Cloud Container Registry
        uses: docker/login-action@v2
        with:
          registry: ccr.ccs.tencentyun.com
#          username: ${{ secrets.TENCENT_REGISTRY_USERNAME }}
#          password: ${{ secrets.TENCENT_REGISTRY_PASSWORD }}
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: junxiezy@930117

#      - name: Build chatchat and push
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          dockerfile: Dockerfile
#          push: true
#          platforms: linux/amd64,linux/arm64
##          tags: ccr.ccs.tencentyun.com/chatchat/chatchat:${{ steps.vars.outputs.sha_short }}
#          tags: ccr.ccs.tencentyun.com/chatchat/chatchat:test

      - name: Build and push Docker image
        run: |
          docker build --volume /mnt:/mnt -t ccr.ccs.tencentyun.com/chatchat/chatchat:latest -f Dockerfile .
          docker push ccr.ccs.tencentyun.com/chatchat/chatchat:latest