name: build

on:
  push:
    branches:
      - "feat/gitAction"

env:
  DOCKERHUB_USERNAME: 100018410921

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/apache/flink/blob/02d30ace69dc18555a5085eccf70ee884e73a16e/tools/azure-pipelines/free_disk_space.sh
      - name: Delete huge unnecessary tools folder
        run: |
          echo "=============================================================================="
          echo "Freeing up disk space on CI system"
          echo "=============================================================================="

          echo "Listing 100 largest packages"
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
          df -h
          echo "Removing large packages"
          sudo apt-get remove -y '^ghc-8.*'
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
          echo "Removing large directories"
          # deleting 15GB
          rm -rf /usr/share/dotnet/
          df -h
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ env.DOCKERHUB_USERNAME }}
##          password: ${{ secrets.DOCKERHUB_TOKEN }}
#          password: junxiezy@930117
      - name: Clone model
        run: |
          git lfs install
          cd ..
          git clone https://huggingface.co/THUDM/chatglm3-6b
          git clone https://huggingface.co/BAAI/bge-large-zh-v1.5
      - name: Login to Tencent Cloud Container Registry
        uses: docker/login-action@v2
        with:
          registry: ccr.ccs.tencentyun.com
#          username: ${{ secrets.TENCENT_REGISTRY_USERNAME }}
#          password: ${{ secrets.TENCENT_REGISTRY_PASSWORD }}
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: junxiezy@930117
      - name: Build chatchat and push
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
#          tags: ccr.ccs.tencentyun.com/chatchat/chatchat:${{ steps.vars.outputs.sha_short }}
          tags: ccr.ccs.tencentyun.com/chatchat/chatchat:test
      # - name: Update helm values.yaml
      #   uses: fjogeleit/yaml-update-action@main
      #   with:
      #     valueFile: 'helm/values.yaml'
      #     commitChange: true
      #     branch: main
      #     message: 'Update Image Version to ${{ steps.vars.outputs.sha_short }}'
      #     changes: |
      #       {
      #         "backend.tag": "${{ steps.vars.outputs.sha_short }}",
      #         "frontend.tag": "${{ steps.vars.outputs.sha_short }}"
      #       }
