name: build

on:
  push:
    branches:
      - "feat/gitAction"

env:
  DOCKERHUB_USERNAME: 100018410921
#  REPO_URL: https://github.com/coolsnowwolf/lede
#  REPO_BRANCH: master
#  FEEDS_CONF: feeds.conf.default
#  CONFIG_FILE: 360T7.config
#  DIY_P1_SH: diy-part1.sh
#  DIY_P2_SH: diy-part2.sh
#  UPLOAD_BIN_DIR: false
#  UPLOAD_FIRMWARE: true
#  UPLOAD_COWTRANSFER: false
#  UPLOAD_WETRANSFER: false
#  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          df -h
          sudo apt-get remove -y '^dotnet-.*' '^llvm-.*' 'php.*' azure-cli google-chrome-stable firefox powershell mono-devel
          sudo apt-get autoremove --purge -y
          sudo apt-get clean
          rm -rf /opt/hostedtoolcache
          sudo find /var/log -name "*.gz" -type f -delete
          sudo rm -rf /var/cache/apt/archives
          sudo rm -rf /tmp/*
          docker rmi $(docker images -q)
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql /etc/php
          sudo -E apt-get -y purge azure-cli* docker* ghc* zulu* hhvm* llvm* firefox* google* dotnet* aspnetcore* powershell* openjdk* adoptopenjdk* mysql* php* mongodb* moby* snap* || true
          sudo -E apt-get -qq update
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo rm -rf /etc/apt/sources.list.d/* /usr/local/lib/android /opt/ghc /usr/share/dotnet /usr/local/graalvm /usr/local/.ghcup \
          /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/node_modules
          sudo timedatectl set-timezone "$TZ"
          sudo chown $USER:$GROUPS $GITHUB_WORKSPACE

#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Set outputs
#        id: vars
#        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2

#      - name: Clone model
#        run: |
#          df -h
#          sudo mkdir -p /mnt/chatglm3-6b /mnt/bge-large-zh-v1.5
#
#          cd /mnt/chatglm3-6b
#          sudo wget https://huggingface.co/THUDM/chatglm3-6b/resolve/main/model-00001-of-00007.safetensors &> /dev/null
#          sudo wget https://huggingface.co/THUDM/chatglm3-6b/resolve/main/model-00002-of-00007.safetensors &> /dev/null
#          sudo wget https://huggingface.co/THUDM/chatglm3-6b/resolve/main/model-00003-of-00007.safetensors &> /dev/null
#          sudo wget https://huggingface.co/THUDM/chatglm3-6b/resolve/main/model-00004-of-00007.safetensors &> /dev/null
#          sudo wget https://huggingface.co/THUDM/chatglm3-6b/resolve/main/model-00005-of-00007.safetensors &> /dev/null
#          sudo wget https://huggingface.co/THUDM/chatglm3-6b/resolve/main/model-00006-of-00007.safetensors &> /dev/null
#          sudo wget https://huggingface.co/THUDM/chatglm3-6b/resolve/main/model-00007-of-00007.safetensors &> /dev/null
#
#          cd /mnt/bge-large-zh-v1.5
#          sudo wget https://huggingface.co/BAAI/bge-large-zh-v1.5/resolve/main/pytorch_model.bin &> /dev/null
#
#          sudo tar -zcf /mnt/chatglm3-6b.tar.gz /mnt/chatglm3-6b
#          sudo tar -zcf /mnt/bge-large-zh-v1.5.tar.gz /mnt/bge-large-zh-v1.5
#
#          sudo mv /mnt/chatglm3-6b.tar.gz ${{ github.workspace }}/
#          sudo mv /mnt/bge-large-zh-v1.5.tar.gz ${{ github.workspace }}/
#          sudo rm -rf /mnt/chatglm3-6b /mnt/bge-large-zh-v1.5
#
#          du -sh ${{ github.workspace }}/*.tar.gz
          
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ env.DOCKERHUB_USERNAME }}
##          password: ${{ secrets.DOCKERHUB_TOKEN }}
#          password: junxiezy@930117

#      - name: Login to Tencent Cloud Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ccr.ccs.tencentyun.com
#          # username: ${{ secrets.TENCENT_REGISTRY_USERNAME }}
#          # password: ${{ secrets.TENCENT_REGISTRY_PASSWORD }}
#          username: ${{ env.DOCKERHUB_USERNAME }}
#          password: junxiezy@930117

      - name: Show runner disk
        run: |
          df -h

#      - name: Build chatchat and push
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          dockerfile: Dockerfile
#          push: true
#          platforms: linux/amd64,linux/arm64
#          # tags: ccr.ccs.tencentyun.com/chatchat/chatchat:${{ steps.vars.outputs.sha_short }}
#          tags: ccr.ccs.tencentyun.com/chatchat/chatchat:test