name: Close inactive issues
on:
  schedule:
    - cron: "30 21 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: "这个问题已经被标记为 `stale` ，因为它已经超过 30 天没有任何活动。"
          close-issue-message: "这个问题已经被自动关闭，因为它被标为 `stale` 后超过 14 天没有任何活动。"
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
