name: label_issue

on:
  issues:
    types:
      - opened

jobs:
  label_issue:
    runs-on: ubuntu-latest

    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          stat=no
          AD_KEYWORDS=(Download Crack "Serial Key" "License Key" "Product Key" "Free Download" "Full Version" "Full Crack" "Full Keygen" "Full License" "Full Activation" "Full Serial")
          ISSUE_TITLE_LOWER=$(echo $ISSUE_TITLE | tr '[:upper:]' '[:lower:]')
          for KEYWORD in ${AD_KEYWORDS[@]}; do
            if [[ $ISSUE_TITLE_LOWER == *$KEYWORD* ]] && [[ $ISSUE_TITLE_LOWER != *input* ]]; then
              stat=yes
              break
            fi
          done
          if [[ $stat == yes ]]; then
            echo "Issue title contains advertisement keywords."
          
            gh issue delete $ISSUE_URL --yes 
          fi